name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Smoke-check artifacts
        run: |
          test -f artifacts/cls_model.joblib || (echo "Missing classifier artifact" && exit 1)
          test -f artifacts/reg_model.joblib || (echo "Missing regressor artifact" && exit 1)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2   # <-- change region if needed

      - name: Install EB CLI
        run: pip install awsebcli

      - name: Initialize EB (idempotent)
        run: |
          eb status || eb init -p docker personal-inflation-impact -r eu-west-2

      - name: Deploy to EB
        run: eb deploy pii-prod
