name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Smoke-check artifacts
        run: |
          test -f artifacts/cls_model.joblib || (echo "Missing classifier artifact" && exit 1)
          test -f artifacts/reg_model.joblib || (echo "Missing regressor artifact" && exit 1)

      - name: Trigger Render deploy
        run: |
          curl -fsSL -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
